title: Streamtime Docs
description: Docs for streamtime.ai
theme: just-the-docs
favicon_ico: /assets/streamtime.svg
url: "https://docs.streamtime.ai"
logo: /assets/streamtime.svg
logo_alt: Streamtime Logo
nav_enable: true
heading_anchors: true
plugins:
  - jekyll-default-layout
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue